language: english
target: jekyll

# Link to home
url: /

destination: _site
image_path: docs
port: 4000
highlighter: rouge
github_editme_path: https://github.com/amzn/appstore-alexa-docs/

image_path: docs
audio_path: docs

markdown: kramdown
kramdown:
 input: GFM
 auto_ids: true
 hard_wrap: false
 syntax_highlighter: rouge

collections:
  docs:
    output: true
  search:
    output: true
  cdf:
    output: true

sass:
    style: compressed

defaults:
  -
    scope:
      path: ""
      type: pages
    values:
      layout: dexwebsite
      topnav: topnav
      tag_group: taglist
  -
    scope:
      path: ""
      type: docs
    values:
#      layout: default_three_column
      layout: dexwebsite
      topnav: topnav
      tag_group: taglist
  -
    scope:
      path: ""
      type: search
    values:
      layout: dexwebsite
      topnav: topnav
      tag_group: taglist
      toc-style: kramdown
      github_button: false
      type: search

exclude:
  - _config*
  - _output_ja
  - _output_de
  - sapp
  - Config

########## UI text ###############


uistring:
    tableofcontents: Table of Contents
    log_doc_issue: Log Doc Issue
    breadcrumb:
      home: Home
      documentation: Documentation
    expandall: Expand All
    collapseall: Collapse All
    title: Amazon Developer Portal # Displays as site title on top nav bar and on site metadata
    description: Documentation for Amazon products, including Fire TV, Fire tablets, Alexa, Appstore, and more.  # Displays as site description meta
    search_placeholder_global: Global Search ...
    search_placeholder_product: Product Search ...
    github_edit_button_text: Edit on GitHub
    search_results_page_title: Search results
    search_no_results_found: No results found.
    products: Products
    docindex_product: Product
    docindex_startpage: Starting page
